version: "3.1"
services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    volumes:
      - verdaccio-config:/verdaccio/config
      - verdaccio-plugins:/verdaccio/plugins
      - verdaccio-storage:/verdaccio/storage
    ports:
      - "4873:4873"
volumes:
  verdaccio-config:
  verdaccio-plugins:
  verdaccio-storage:
networks:
  node-network:
    driver: bridge
